---
title: "Exploratory Data Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---


```{r setup, include=FALSE}
library(tidyverse)
library(mgcv)
library(modelr)
library(viridis)
library(labelled)
library(table1)
library(patchwork)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "100%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r import, include=FALSE}
#Importing the datasets
federal_df <- load("./data/04572-0001-Data.rda") 

federal_df <- da04572.0001 %>% 
  select(V2288, V2289, V2290, V2291, MCMH_HIVTEST, MCMH_RSLT_HIV, DRUG_INJECT_CB, V2401, V2402, V2403, V2404, V2405, V2406, V2407, V2409, V2412, MCMH_MH_TREATMENT_PA, MCMH_MH_TREATMENT_AD, MCMH_MENTAL_HISTORY, V1197, CS_SENTENCEMTH,CH_PRIORSENTENCE, CH_PRIORSENTENCE_NUM, CH_CRIMHIST, CH_CRIMHIST_COLLAPSED, CH_NUMCAR,CH_NUMCAR1, CH_NUMCAR2, CH_NUMCAR3, CH_NUMCAR4, CH_NUMCAR5, MOST_SERIOUS_OFFENSE2, TYPEOFFENSE, V1056, V1057, V1060, V1061, V1325, V0001, V0014, AGE_CAT, V2982, V0005, EDUCATION, SES_INCOMEMTH, DRUG_ANY, DRUG_ANYREG, DRUG_ANYMTH, SES_PHYSSEXABUSED_EVER, SES_PARENTS_INCARCERATED, SES_FAMILY_INCARCERATED, V0105, MCMH_WHEN_DISORDER, MCMH_WHEN_DISORDER2,MCMH_MHOSPYR,MCMH_MHOSPADM,MCMH_MHOSPYRADM,MCMH_SMI) %>%
  mutate(dataset = "Federal")

state_df <- load("./data/04572-0002-Data.rda") 

state_df <- da04572.0002 %>% 
   select(V2288, V2289, V2290, V2291, MCMH_HIVTEST, MCMH_RSLT_HIV, DRUG_INJECT_CB, V2401, V2402, V2403, V2404, V2405, V2406, V2407, V2409, V2412, MCMH_MH_TREATMENT_PA, MCMH_MH_TREATMENT_AD, MCMH_MENTAL_HISTORY, V1197, CS_SENTENCEMTH,CH_PRIORSENTENCE, CH_PRIORSENTENCE_NUM, CH_CRIMHIST, CH_CRIMHIST_COLLAPSED, CH_NUMCAR,CH_NUMCAR1, CH_NUMCAR2, CH_NUMCAR3, CH_NUMCAR4, CH_NUMCAR5, MOST_SERIOUS_OFFENSE2, TYPEOFFENSE, V1056, V1057, V1060, V1061, V1325, V0001, V0014, AGE_CAT, V2982, V0005, EDUCATION, SES_INCOMEMTH, DRUG_ANY, DRUG_ANYREG, DRUG_ANYMTH, SES_PHYSSEXABUSED_EVER, SES_PARENTS_INCARCERATED, SES_FAMILY_INCARCERATED, V0105, MCMH_WHEN_DISORDER, MCMH_WHEN_DISORDER2,MCMH_MHOSPYR,MCMH_MHOSPADM,MCMH_MHOSPYRADM,MCMH_SMI) %>%
  mutate(dataset = "State")
```

```{r combine_clean, include=FALSE}
#Combining datasets, filtering dataset, formatting variables
total_df = 
  bind_rows(state_df, federal_df) %>% 
  mutate(
    dataset = as.factor(dataset)) %>%
  mutate(
    MENTAL_HISTORY_BINARY = case_when(MCMH_MENTAL_HISTORY == "(0000001) Yes" ~ "1", MCMH_MENTAL_HISTORY == "(0000002) No" ~ "0", MCMH_MENTAL_HISTORY == "(9999997) DK/refused" | MCMH_MENTAL_HISTORY == "(9999999) Blank"  ~ ".")) %>%
  mutate(
    MENTAL_HISTORY_BINARY = na_if(MENTAL_HISTORY_BINARY, "."), 
    MENTAL_HISTORY_BINARY = factor(MENTAL_HISTORY_BINARY, 
      levels = c(0, 1),
      labels = c("No history of mental health condition(s)", "History of mental health condition(s)")))  %>% 
  filter(!is.na(MENTAL_HISTORY_BINARY)) %>% 
  mutate(V0005 = dplyr::recode(V0005, "(1) Male" = "Male", "(2) Female" = "Female")) %>% 
  mutate(AGE_CAT = dplyr::recode(AGE_CAT, "(1) < 25 yrs" = "< 25 yrs", "(2) 25-34" = "25-34", "(3) 35-44" =  "35-44", "(4) 45-54" = "45-54", "(5) 55-64" = "55-64", "(6) 65-96" = "65-96", "(7) Unknown" = "Unknown")) %>% 
  mutate(
    V2982 = dplyr::recode(V2982, "(1) White non-Hispanic" = "White non-Hispanic", "(2) Black non-Hispanic" = "Black non-Hispanic", "(3) Hispanic" = "Hispanic", "(4) American Indian, Alaska Native non-Hispanic" = "American Indian, Alaska Native non-Hispanic", "(5) Asian, Pacific Islander, Native Hawaiian non-Hispanic" = "Asian, Pacific Islander, Native Hawaiian non-Hispanic", "(6) Multiple Races reported, non-Hispanic" = "Multiple Races reported, non-Hispanic", "(8) Other, Uncategorized - Missing" = "NA"), 
    V2982 = factor(V2982, exclude = "NA"), 
    V2982 = na_if(V2982, "NA")) %>% 
  mutate(
    EDUCATION = dplyr::recode(EDUCATION, "(0000000) Never attended or attended kindergarten only" = "Never attended or attended kindergarten only", "(0000001) First grade" = "First grade", "(0000002) Second grade" = "Second grade", "(0000003) Third grade" = "Third grade", "(0000004) Fourth grade" = "Fourth grade", "(0000005) Fifth grade" = "Fifth grade", "(0000006) Sixth grade" = "Sixth grade", "(0000007) Seventh grade" = "Seventh grade", "(0000008) Eighth grade" = "Eighth grade", "(0000009) Ninth grade" = "Ninth grade", "(0000010) Tenth grade" = "Tenth grade", "(0000011) Eleventh grade" = "Eleventh grade", "(0000012) Twelfth grade" = "Twelfth grade", "(0000013) College freshman" = "College freshman", "(0000014) College sophomore" = "College sophomore", "(0000015) College junior" = "College junior", "(0000016) College senior" = "College senior", "(0000017) Graduate school one year" = "Graduate school one year", "(0000018) Graduate school two or more years" = "Graduate school two or more years", "(0000019) Attended school in other country/system not comparable to grades" = "Attended school in other country/system not comparable to grades", "(9999997) Don't know" = "Don't know", "(9999998) Refused" = "NA", "(9999999) Missing" = "NA"), 
    EDUCATION = factor(EDUCATION, exclude = "NA"), 
    EDUCATION = na_if(EDUCATION, "NA")) %>% 
  mutate(
    SES_INCOMEMTH = dplyr::recode(SES_INCOMEMTH, "(0000000) No income" = "No income", "(0000001) $1 - 199" = "$1 - $199", "(0000002) 200 - 399" = "$200 - $399", "(0000003) 400 - 599" = "$400 - $599", "(0000004) 600 - 799" = "$600 - $799", "(0000005) 800 - 999" = "$800 - $999", "(0000006) 1,000 - 1,199" = "$1,000 - $1,199", "(0000007) 1,200 - 1,499" = "$1,200 - $1,499", "(0000008) 1,500 - 1,999" = "$1,500 - $1,999", "(0000009) 2,000 - 2,499" = "$2,000 - $2,499", "(0000010) 2,500 - 4,999" = "$2,500 - $4,999", "(0000011) 5,000 - 7,499" = "$5,000 - $7,499", "(0000012) 7,500 or more" = "$7,500 or more", "(9999997) Don't know" = "Don't know", "(9999998) Refused" = "NA", "(9999999) Missing" = "NA"), 
    SES_INCOMEMTH = factor(SES_INCOMEMTH, exclude = "NA"), 
    SES_INCOMEMTH = na_if(SES_INCOMEMTH, "NA")) %>% 
  mutate(
    CH_PRIORSENTENCE_NUM = dplyr::recode(CH_PRIORSENTENCE_NUM, "(0000000) No prior sentence" = "No prior sentence", "(0000001) One prior sentence" = "One prior sentence", "(0000002) Two prior sentences" = "Two prior sentences", "(0000003) Three to five prior sentences" = "Three to five prior sentences", "(0000004) Six to ten prior sentences" = "Six to ten prior sentences", "(0000005) Eleven or more prior sentences" = "Eleven or more prior sentences", "(9999999) Missing" = "NA"), 
    CH_PRIORSENTENCE_NUM = factor(CH_PRIORSENTENCE_NUM, exclude = "NA"), 
    CH_PRIORSENTENCE_NUM = na_if(CH_PRIORSENTENCE_NUM, "NA")) %>% 
    mutate(
    V1197 = ifelse(V1197 <= 996, V1197, NA)) %>% 
  mutate(
    CH_CRIMHIST_COLLAPSED = dplyr::recode(CH_CRIMHIST_COLLAPSED, "(0000001) First timers" = "First timers", "(0000002) Recidivist, current or past violent offense" = "Recidivist, current or past violent offense", "(0000003) Recidivist, no current or prior violent offense" = "Recidivist, no current or prior violent offense", "(9999999) Missing" = "NA"), 
    CH_CRIMHIST_COLLAPSED = factor(CH_CRIMHIST_COLLAPSED, exclude = "NA"), 
    CH_CRIMHIST_COLLAPSED = na_if(CH_CRIMHIST_COLLAPSED, "NA")) %>% 
  mutate(
    SES_PARENTS_INCARCERATED = dplyr::recode(SES_PARENTS_INCARCERATED, "(0000001) Yes" = "Yes", "(0000002) No" = "No","(9999997) Don't know" = "NA", "(9999998) Refused" = "NA", "(9999999) Missing" = "NA"), 
    SES_PARENTS_INCARCERATED = factor(SES_PARENTS_INCARCERATED, exclude = "NA"), 
    SES_PARENTS_INCARCERATED = na_if(SES_PARENTS_INCARCERATED, "NA")) %>% 
  mutate(
    SES_FAMILY_INCARCERATED = dplyr::recode(SES_FAMILY_INCARCERATED, "(0000001) Yes" = "Yes", "(0000002) No" = "No","(9999997) Don't know" = "NA", "(9999998) Refused" = "NA", "(9999999) Missing" = "NA"), 
    SES_FAMILY_INCARCERATED = factor(SES_FAMILY_INCARCERATED, exclude = "NA"), 
    SES_FAMILY_INCARCERATED = na_if(SES_FAMILY_INCARCERATED, "NA")) %>% 
  set_variable_labels(dataset = "Dataset", MENTAL_HISTORY_BINARY = "Binary Mental Health History", V0005 = "Sex", AGE_CAT = "Age Group", V2982 = "Race/Ethnicity", EDUCATION = "Education", SES_INCOMEMTH = "Monthly Income in Month Before Arrest", CH_PRIORSENTENCE_NUM = "Number of Prior Sentences", V1197 = "Number of Prior Arrests", CH_CRIMHIST_COLLAPSED = "Collapsed Criminal History", TYPEOFFENSE = "Type of Offense", SES_PARENTS_INCARCERATED = "Parents Been Incarcerated", SES_FAMILY_INCARCERATED = "Children, Siblings, or Spouse Been Incarcerated")
```

# Demographics

```{r demographics}
#Table 1
table1(~ V0005 + AGE_CAT + V2982 | MENTAL_HISTORY_BINARY, data = total_df, overall = "Total")

#BAR GRAPH FOR EDUCATION



#BAR GRAPH FOR SES_INCOMEMTH


```


# Incarceration-Related Variables

```{r incarceration}
#Table 1
table1(~ CH_PRIORSENTENCE_NUM + V1197 + CH_CRIMHIST_COLLAPSED + SES_PARENTS_INCARCERATED + SES_FAMILY_INCARCERATED | MENTAL_HISTORY_BINARY, data = total_df, overall = "Total")

#BAR GRAPH FOR TYPEOFOFFENSE


#DENSITY PLOT FOR V1197


```


# HIV

Our initial interest was in HIV prevalence and predictors in the prison system. We performed some exploratory analyses:
```{r HIV counts}
state_df %>%
  group_by(MCMH_RSLT_HIV)%>%
  summarise(count = n()) %>%
  mutate(percent = (count / sum(count))) %>%
  knitr::kable()
```

# Mental Health

```{r mental_health}
#ever taken a medication for mental health 
federal_df %>% 
  group_by(V2409) %>% 
  summarize(count = n()) %>% 
  knitr::kable()

federal_df %>% 
  group_by(V2409) %>% 
  summarize(n_obs = n()) %>% 
   mutate(
    V2409 = fct_reorder(V2409, n_obs)) %>% 
  ungroup() %>% 
  ggplot(aes(x = V2409, y = n_obs, fill = V2409)) +
  geom_bar(stat = "identity")

# TAKEN MEDICATION FOR A MENTAL CONDITION SINCE ADMISSION
federal_df %>% 
  group_by(V2412) %>% 
  summarize(n_obs = n()) %>% 
  knitr::kable()

federal_df %>% 
  group_by(V2412) %>% 
  summarize(n_obs = n()) %>% 
  drop_na() %>% 
   mutate(
    V2412 = fct_reorder(V2412, n_obs)) %>% 
  ungroup() %>% 
  ggplot(aes(x = V2412, y = n_obs, fill = V2412)) +
  geom_bar(stat = "identity")

# Mental Hosp - year before arrest - MCMH_mhospyr from client
federal_df %>% 
  group_by(MCMH_MHOSPYR) %>% 
  summarize(n_obs = n()) %>% 
  knitr::kable()

federal_df %>% 
  group_by(MCMH_MHOSPYR) %>% 
  summarize(n_obs = n()) %>% 
  filter(MCMH_MHOSPYR %in% c("(0000004) No, never admitted to stayed overnight at mental hospital","(0000001) Yes, admitted to mental hospital during the 12 months before arrest",
  "(0000002) No, was not admitted to mental hospital during the 12 months before arrest")) %>% 
  drop_na() %>% 
   mutate(
    MCMH_MHOSPYR = fct_reorder(MCMH_MHOSPYR, n_obs)) %>% 
  ungroup() %>% 
  ggplot(aes(x = MCMH_MHOSPYR, y = n_obs, fill = MCMH_MHOSPYR)) +
  geom_bar(stat = "identity")

# Mental hosp - since admission - MCMH_mhospadm from client
federal_df %>% 
  group_by(MCMH_MHOSPADM) %>% 
  summarize(n_obs = n()) %>% 
  knitr::kable()

federal_df %>% 
  group_by(MCMH_MHOSPADM) %>% 
  summarize(n_obs = n()) %>% 
    filter(!MCMH_MHOSPADM %in% c("(9999999) Missing","(9999998) DK/refused")) %>% 
  drop_na() %>% 
   mutate(
    MCMH_MHOSPADM = fct_reorder(MCMH_MHOSPADM, n_obs)) %>% 
  ungroup() %>% 
  ggplot(aes(x = MCMH_MHOSPADM, y = n_obs, fill = MCMH_MHOSPADM)) +
  geom_bar(stat = "identity")


# MH Treatment Continuation (one year prior to arrest and since admission)

state_tx = state_df %>%
  group_by(MCMH_MH_TREATMENT_PA, MCMH_MH_TREATMENT_AD) %>%
  summarize(n_obs = n()) %>%
  mutate(
    MCMH_MH_TREATMENT_PA = gsub(".* ", "", MCMH_MH_TREATMENT_PA),
    MCMH_MH_TREATMENT_AD = gsub(".* ", "", MCMH_MH_TREATMENT_AD),
    tx_pa_ad = str_c(MCMH_MH_TREATMENT_PA, '/',MCMH_MH_TREATMENT_AD)
  ) %>%
  ungroup() %>%
  mutate(
    sum = sum(n_obs),
    percent = (n_obs/sum) * 100 ) 

federal_tx = federal_df %>%
  group_by(MCMH_MH_TREATMENT_PA, MCMH_MH_TREATMENT_AD) %>%
  summarize(n_obs = n()) %>%
  mutate(
    MCMH_MH_TREATMENT_PA = gsub(".* ", "", MCMH_MH_TREATMENT_PA),
    MCMH_MH_TREATMENT_AD = gsub(".* ", "", MCMH_MH_TREATMENT_AD),
    tx_pa_ad = str_c(MCMH_MH_TREATMENT_PA, '/',MCMH_MH_TREATMENT_AD)
  ) %>%
  ungroup() %>%
  mutate(
    sum = sum(n_obs),
    percent = (n_obs/sum) * 100 ) 

colors <- c("State Prisons" = "blue", "Federal Prisons" = "red")
ggplot() + 
  geom_line(data = state_tx, aes(x = tx_pa_ad, y = percent, group = 1, color = "State Prisons")) + 
  geom_line(data = federal_tx, aes(x = tx_pa_ad, y = percent, group = 1, color = "Federal Prisons")) +
  labs(
    title = "Mental Health Treatment Continuation",
    x = "1 Year Prior to Arrest/Since Admission",
    y = "Percent (%) of Survey Respondents",
    color = "Legend"
  ) +
  scale_color_manual(values = colors)
```

#Associations Between HIV & Mental Health

```{r hiv mh}

#Overall 
total_df %>%
  group_by(MCMH_RSLT_HIV)%>%
  summarise(count = n()) %>%
  mutate(percent = (count / sum(count))) %>%
  knitr::kable()

#Graph state vs. Prison
federal_bar = 
  federal_df %>%
  group_by(MCMH_RSLT_HIV, MCMH_MENTAL_HISTORY)%>%
  summarise(count = n()) %>%
  mutate(percent = (count / sum(count))) %>%
      filter(MCMH_RSLT_HIV != "(9999999) Missing",
           MCMH_MENTAL_HISTORY == "(0000001) Yes") %>%
  mutate(HIV_status = recode(MCMH_RSLT_HIV, 
      "(0000001) At least one positive test" = "Positive", 
      "(0000002) At least one negative and the other unknown" = "Negative")) %>%
  ggplot(aes(x = HIV_status, y = percent)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title="Federal",
        x ="HIV Status", y = "Percent with Mental Health Disorder") +
  ylim(0, 0.5)

state_bar = 
  state_df %>%
  group_by(MCMH_RSLT_HIV, MCMH_MENTAL_HISTORY)%>%
  summarise(count = n()) %>%
  mutate(percent = (count / sum(count))) %>%
      filter(MCMH_RSLT_HIV != "(9999999) Missing",
           MCMH_MENTAL_HISTORY == "(0000001) Yes") %>%
  mutate(HIV_status = recode(MCMH_RSLT_HIV, 
      "(0000001) At least one positive test" = "Positive", 
      "(0000002) At least one negative and the other unknown" = "Negative")) %>%
  ggplot(aes(x = HIV_status, y = percent)) +
  geom_bar(stat = "identity", fill = "red") +
  labs(title="State",
        x ="HIV Status", y = "Percent with Mental Health Disorder") +
  ylim(0, 0.5)

#Mental Health Disorder Prevalence by HIV Status at the Federal & State Levels(2004)
federal_bar + state_bar
```
