---
title: "Mapping"
output: 
  html_document:
    toc: true
    code_folding: hide
    toc_float: true
    theme: flatly
---

```{r setup, include=FALSE}
library(tidyverse)
library(mgcv)
library(modelr)
library(viridis)
library(labelled)
library(table1)
library(patchwork)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "100%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r collect and export data to be mapped}

total_df %>% 
  group_by(V1056) %>% 
  summarize(
    count = n(),
    HIV = sum(MCMH_RSLT_HIV == "(0000001) At least one positive test"),
    MH_Status = sum(MENTAL_HISTORY_BINARY == "History of mental health condition(s)"),
    MH_Treat_Prior = sum(MCMH_MH_TREATMENT_PA == "(1) Yes"),
    MH_Treat_Admission = sum(MCMH_MH_TREATMENT_AD == "(1) Yes")) %>%
   mutate(
    V1056 = fct_reorder(V1056, count),
    V1056 = str_sub(V1056, 6)) %>% 
  rename(Residence_at_arrest = V1056) %>%
  write.csv("./mapping.csv", row.names=TRUE)

```

